# Workflow derived from https://github.com/r-lib/actions
name: Build and Release R Package

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: r-lib/actions/setup-pandoc@v2
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true
      
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::devtools
            any::roxygen2
            any::pkgbuild
          needs: workflow
      
      - name: Document
        run: roxygen2::roxygenise()
        shell: Rscript {0}
      
      - name: Build package
        id: build
        run: |
          pkg_file <- pkgbuild::build()
          pkg_name <- basename(pkg_file)
          # Use the new GITHUB_OUTPUT environment file approach
          writeLines(paste0("pkg_file=", pkg_file), Sys.getenv("GITHUB_OUTPUT"))
          writeLines(paste0("pkg_name=", pkg_name), Sys.getenv("GITHUB_OUTPUT"))
        shell: Rscript {0}
      
      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: r-package
          path: ${{ steps.build.outputs.pkg_file }}
      
      - name: Deploy to gh-pages
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'release'
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          
          # Create or switch to gh-pages branch
          git checkout -B gh-pages
          
          # Clear the branch and copy the package
          git rm -rf .
          cp ${{ steps.build.outputs.pkg_file }} .
          
          # Create an index.html with instructions
          cat > index.html << EOF
          <!DOCTYPE html>
          <html>
            <head>
              <title>binaryClass R Package</title>
            </head>
            <body>
              <h1>binaryClass R Package</h1>
              <p>Install the latest version with:</p>
              <pre>
          install.packages("https://codoom1.github.io/binaryClass/${{ steps.build.outputs.pkg_name }}", repos = NULL)
              </pre>
            </body>
          </html>
          EOF
          
          # Add both files and commit
          git add ${{ steps.build.outputs.pkg_name }} index.html
          git commit -m "Update package to latest version"
          
          # Force push to gh-pages 